version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: banco_postgres
    restart: always
    environment:
      POSTGRES_DB: project_bank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
